In [1]:
import time
import requests
import json
import os
import pandas as pd
import base64
import csv

In [2]:
def get_artist_list():
    
    csv_file = r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\artists_db\DM_bands.csv'
    #csv_file = '/home/pi/myProjects/Python/Spotify_v2/artists_db/F_10_bands.csv' 
        
    #'''
    #csv_path = '/home/pi/myProjects/Python/Spotify_v2/artists_db/'
    with open(csv_file, 'r') as infile:
        reader = csv.reader(infile)
        name_gender = []
        artist_list=[]
        for col in reader:
            artist_list.append((col[1]))
            
    infile.close()
    artist_list.pop(0)
    #'''
    
    del reader, col
    
    return artist_list

In [3]:
def get_access_token():

    # URLS
    AUTH_URL    = 'https://accounts.spotify.com/authorize'
    TOKEN_URL   = 'https://accounts.spotify.com/api/token'
    CLIENT_ID   = '17d35b6f7c6140969fbea4f258d4b72a'
    CLIENT_SECRET = '2e2d4cbba9b5468886b08d74c2767e5a'

    # Ver Autorization Code Flow: 'https://developer.spotify.com/documentation/general/guides/authorization/code-flow/'
    auth_params = {
        'client_id': CLIENT_ID,
        'response_type': 'code',
        'redirect_uri': 'http://localhost:8888/callback',
        'scope': 'user-read-private',
    }
        
    auth_code = requests.get(AUTH_URL, auth_params)
    auth_header = base64.urlsafe_b64encode(bytes(CLIENT_ID + ':' + CLIENT_SECRET, 'utf-8'))
    
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'Basic %s' % auth_header.decode('ascii')
    }

    payload = {
        'grant_type': 'client_credentials',
        'code': auth_code,
        'redirect_uri': 'https://open.spotify.com/collection/playlists',
    }

    # request to /token endpoint. aquí obtenermos el token de acceso 
    access_token_request = requests.post(url=TOKEN_URL, data=payload, headers=headers)
    access_token_response_data = access_token_request.json()

    # extraemos y almacenamos únicamente el token del json
    access_token = access_token_response_data['access_token']

    return  access_token

In [4]:
def search_artist(atoken, BASE_URL, name):
    pass
    search_headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + atoken
    }
    search_pamans = {
        'q': name, 
        'type':'artist',
        'limit':50,
        'offset': 0,
        'include_external': 'FALSE'
        
    }

    new_search_status = requests.get( BASE_URL + 'search?', headers=search_headers, params=search_pamans)
    new_search = new_search_status.json()
    
    line = (name + ',' + atoken['token_type'] + ':' + atoken['access_token'] + ',' + str(new_search_status.status_code) + '\n')
    
    with open('/home/pi/myProjects/Python/Spotify_v3/exec_logs/search_status.txt', 'a') as request_status:
        request_status.write(line)
        request_status.close()
    
    return new_search

In [5]:
import os
def write_to_csv(asearch):
    
    csv_path = r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\_list_artist.csv'
    csv_data = pd.DataFrame()
    csv_data = pd.json_normalize(asearch['artists']['items'],max_level=1)
    csv_data = csv_data.reset_index(drop=True)
    
    if len(csv_data)==0:
        csv_data = csv_data.reset_index(drop=True)
    else:
        csv_data = csv_data.drop(columns=["images","uri","external_urls.spotify","followers.href"])
        csv_data = csv_data.reset_index(drop=True)
    #print(csv_data)            # imprime el dataframe en pantalla
    csv_data.to_csv(csv_path,index=False,mode='a')
    
    del asearch, csv_data
    
    return 0

In [ ]:
def validate_token_expire(atoken, token_start_time):
    status = 1
    token_end_time = time.perf_counter() 
        
    try:
        token_actual_time = round((token_end_time-token_start_time),0) 
        
        if (token_actual_time) >= (atoken['expires_in']-100):
        
            del atoken, token_start_time, token_actual_time
            status = 0
    except Exception:
        status = 0
    
    return status

In [6]:
def clean_csv_duplicated():
    csv_path = os.getcwd() + '/temp_csv_files/'
    #csv_path = os.path.dirname(__file__)
    with open(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\_list_artist.csv', 'r') as infile, open(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\Final_list_artist.csv','w') as outfile:
        seen = set()
        for line in infile:
            if line in seen: continue
            
            seen.add(line)
            outfile.write(line)
        
        infile.close()
        outfile.close()
                
    del csv_path, infile, line, seen
    return 0

In [7]:
def remove_csv_columns():
    #csv_path = os.path.dirname(__file__) + '/temp_csv_files/'
    with open(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\Final_list_artist.csv', 'r') as infile, open(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\Final_list_artist_v2.csv','w') as outfile:
        
        count = 0
        for line in infile:
            if line[0:3] == '[],':
                count = count + 1
            else:         
                outfile.write(line)
        infile.close()
        outfile.close()
                
    del  infile, line
    return 0

In [8]:
def remove_csv_files():
    #csv_path = os.getcwd() + '/temp_csv_files/'
    os.remove(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\_list_artist.csv')
            
    return 0

In [9]:
def main():
    BASE_URL    = 'https://api.spotify.com/v1/'
    atoken = get_access_token()

    artist_name = get_artist_list()

    for a_name in artist_name:
        time.sleep(0.1)
        asearch = search_artist(atoken, BASE_URL, a_name)
        returned_value = write_to_csv(asearch)
        del asearch, returned_value
    returned_value = clean_csv_duplicated()
    time.sleep(0.01)
    returned_value = remove_csv_columns()
    returned_value = remove_csv_files()
    del returned_value
    return 0

In [10]:
main()

0

In [14]:
df_Final_list_artist = pd.read_csv(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\Final_list_artist_v2.csv', encoding='iso8859_2')
df_Final_list_artist['genres'] = df_Final_list_artist['genres'].astype('str')
df_Final_list_artist['genres'] = df_Final_list_artist['genres'].str.replace("'", "")
df_Final_list_artist['genres'] = df_Final_list_artist['genres'].str.replace("[", "")
df_Final_list_artist['genres'] = df_Final_list_artist['genres'].str.replace("]", "")
df_Final_list_artist['genres'] = df_Final_list_artist['genres'].str.replace(",", "")
df_Final_list_artist = df_Final_list_artist.drop(['type', 'href'], axis=1)
df = df_Final_list_artist[(df_Final_list_artist['genres'].str.contains('death metal'))]
df

C:\Users\nelso\miniconda32\envs\Final_Project\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  after removing the cwd from sys.path.
C:\Users\nelso\miniconda32\envs\Final_Project\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """

,genres,id,name,popularity,followers.total
1,progressive technical death metal technical de...,2yQwuvF6qxv98dqMrZ8iTm,Atlantis Chronicles,33,8577
14,dissonant death metal,5YksM5fILg5LIjctxBfSrX,Vertebra Atlantis,9,780
31,german death metal,35BDie84XyB1qcg9hq4Wif,Atomwinter,4,1559

In [27]:
df_DM_bands = pd.read_csv(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\artists_db\DM_bands.csv', encoding='iso8859_2')
df_DM_bands['name'] = df_DM_bands['name'].str.lower() 
df_DM_bands

,id,name,country,status,formed_in,genre,theme,active,Unnamed: 8,Unnamed: 9
0,1,('m') inc.,United States,Unknown,2009.0,Death Metal,NaN,2009-?,NaN,NaN
1,2,(sic),United States,Split-up,1993.0,Death Metal,NaN,1993-1996,NaN,NaN
2,3,.f.o.a.d.,France,Active,2009.0,Death Metal,Life and Death,2009-present,NaN,NaN
3,4,100 suns,United States,Active,2004.0,Death Metal,NaN,2004-present,NaN,NaN
4,5,12 days of anarchy,United States,Split-up,1998.0,Death Metal,Anarchy,1998-2002,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
37718,37719,gladiator,Slovakia,Active,1988.0,Death/Thrash Metal (1988-93)| Grunge/Hard Rock...,Sorrow| Nuclear War| Doom,1988-present,NaN,NaN
37719,37720,innersight,Hungary,Active,1997.0,Post-Rock (early)| Progressive Death Metal (mi...,NaN,1997-present,NaN,NaN
37720,37721,lunarsapian,International,Active,2008.0,Black/Death/Doom Metal (early)| Drone/Dark Amb...,NaN,2008-present,NaN,NaN
37721,37722,subconscious,Germany,Active,1990.0,Progressive Thrash/Death Metal (1992| 2002-pre...,NaN,1990-1997| 2002-present,NaN,NaN
37722,37723,frozen mist,United States,Active,2004.0,Gothic Metal (2004-2006)| Melodic Death/Gothic...,Darkness| Despair| Death| Horror| Pagan Ancestry,2004-2014| 2014-2016| 2016-present,NaN,NaN

In [28]:
df_List_artist_2_2  = pd.read_csv(r'C:\Users\nelso\Desktop\ironhacktareas\Final_Project\Spotify_v2.2\Spotify_v2\temp_csv_files\Final_list_artist_v2.csv', encoding='iso8859_2')
df_List_artist_2_2 ['genres'] = df_List_artist_2_2['genres'].astype('str')
df_List_artist_2_2 ['genres'] = df_List_artist_2_2['genres'].str.replace("'", "")
df_List_artist_2_2 ['genres'] = df_List_artist_2_2['genres'].str.replace("[", "")
df_List_artist_2_2 ['genres'] = df_List_artist_2_2['genres'].str.replace("]", "")
df_List_artist_2_2 ['genres'] = df_List_artist_2_2['genres'].str.replace(",", "")
df_List_artist_2_2  = df_List_artist_2_2 .drop(['type', 'href'], axis=1)
df_List_artist_2_2['name'] = df_List_artist_2_2['name'].str.lower() 
df_List_artist_2_2 = df_List_artist_2_2 [(df_List_artist_2_2 ['genres'].str.contains('death metal'))]
df_List_artist_2_2

C:\Users\nelso\miniconda32\envs\Final_Project\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  after removing the cwd from sys.path.
C:\Users\nelso\miniconda32\envs\Final_Project\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """

,genres,id,name,popularity,followers.total
31,colombian death metal,5OwPAhftA8RDjcNFNIcIi5,inbreeding sick,33,259
102,"brutal death metal ""death n roll"" death metal ...",4pFAF1L1tYnJHLe5hgyKuI,six feet under,45,145372
105,french death metal,6WL6xlSqEs8k4lFbjd03bn,the seven gates,0,64
134,italian death metal,1zrhIsvPOMNgoHW9YLESlq,a place for murder,0,66
186,goregrind irish death metal irish metal,7JiGOjZmUWZWyhhQsyBZs4,abaddon incarnate,5,865
...,...,...,...,...,...
31949,florida death metal,48xKhMwR27gMs5corijsNt,order of ennead,2,706
31957,colombian death metal,2DMTxnsEUkARl8oroZ90ts,ordog,0,24
32012,cavernous death metal,79tFEqKUbOncVYJY75vZu2,ossuarium,7,3842
32035,cavernous death metal voidgrind,0TqeBKIm8KAKw6DYwUXqMQ,our place of worship is silence,13,4725
32041,death metal groove metal hard rock metal old s...,0NmYchKQ8JIR9QHYJA0FRe,overkill,49,445609

In [29]:
Big_DT = pd.merge(df_DM_bands, df_List_artist_2_2, on='name') 
#Big_DT = pd.concat(df_DM_bands, df_List_artist_2_2)
#Big_DT = df_DM_bands.merge(df_List_artist_2_2,how='right')
Big_DT = Big_DT.drop(['Unnamed: 8', 'Unnamed: 9', 'genres', 'id_y', 'id_x' ], axis=1)
Big_DT

,name,country,status,formed_in,genre,theme,active,popularity,followers.total
0,a place for murder,Italy,Active,2009.0,Death Metal,Death| Life| Nature| Technology| Human Madness,2009-2012| 2013-present,0,66
1,abhordium,Finland,Active,2005.0,Death Metal,Death| Society| Misanthropy| Occultism,2005-present,1,286
2,abhorrence,Finland,Unknown,1989.0,Death Metal,Death| Decay| Pain| Perversion,1989-1990| 2012-?,11,1803
3,abhorrence,Germany,Split-up,NaN,Death Metal,NaN,NaN,11,1803
4,abhorrence,South Africa,Split-up,1992.0,Death Metal,Christianity,1992-1994,11,1803
...,...,...,...,...,...,...,...,...,...
3347,fallujah,United States,Active,2007.0,Blackened Deathcore (early)| Progressive/Techn...,Religious Fundamentalism| Philosophy| Nature| ...,2007-present,39,64353
3348,napalm death,United Kingdom,Active,1981.0,Hardcore Punk (early)| Grindcore/Death Metal (...,Political unrest| Hate| Anti-fascism| Social i...,1981-present,49,263481
3349,the faceless,United States,Active,2004.0,Technical Deathcore (early)| Progressive/Techn...,Science Fiction| Conspiracy| Atheism| Anti-Rel...,2004-present,41,119716
3350,noctiferia,Slovenia,Active,1994.0,Melodic Black Metal/Symphonic Black/Death Meta...,Anti-Capitalism| Anti-Religion,1992-1994 (as Emetica)| 1994-present,6,874
3351,cynic,United States,Disputed,1987.0,Thrash Metal (early)| Progressive Death Metal/...,Personal thoughts| Philosophy| Peace,1987-1994| 1994-1996 (as Portal)| 2006-2015,41,94708

In [ ]:
CSV_Big_DT = Big_DT.to_csv
CSV_Big_DT